version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tarefas
    volumes:
      - /data/mysql
    ports:
      - 3307:3306
  web:
    image: tarefas
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080